#!/bin/bash

echo Which user would you like to install this to? 
read user

echo Copying files to /home/$user/

echo Copying rc files
cp -v .bashrc .vimrc /home/$user/

echo Copying .config folder
cp -rv .config /home/$user/ 

echo Copying .wallpapers folder
cp -rv .wallpapers /home/$user/

echo Copying .welcome folder
cp -rv .welcome /home/$user/

echo Copying /usr/ folder
cp -rv ./usr/* /usr/